DATA_PATH = '/dev/shm/mycar/data'
DRIVE_LOOP_HZ = 30

HAVE_AHRS = True
HAVE_INA226 = True

HAVE_REVCOUNT = True
if HAVE_REVCOUNT:
	REV_RPM_MAX = 15000

	PINION_GEAR = 27
	SPUR_GEAR = 64
	#SPUR_GEAR = 68
	BEVEL_GEAR = 15
	RING_GEAR = 39
	TYRE_DIAMETER = 65
	#TYRE_DIAMETER = 70 #rally block tyre
	GEAR_RATIO = (PINION_GEAR / SPUR_GEAR * BEVEL_GEAR / RING_GEAR)
	KMPH = (GEAR_RATIO * TYRE_DIAMETER * 3.141592 * 60 / 1000 / 1000)

PWM_CENTER = 1520
PWM_MIN    = PWM_CENTER-420 #1070
PWM_MAX    = PWM_CENTER+420 #1970

DRIVE_TRAIN_TYPE = "PIGPIO_PWM"
if DRIVE_TRAIN_TYPE == "PIGPIO_PWM":
	STEERING_PWM_PIN = 12
	STEERING_PWM_FREQ = 100
	STEERING_PWM_INVERTED = False
	THROTTLE_PWM_PIN = 13
	THROTTLE_PWM_FREQ = 100
	THROTTLE_PWM_INVERTED = False
	STEERING_LEFT_PWM = PWM_MIN
	STEERING_RIGHT_PWM = PWM_MAX
	THROTTLE_FORWARD_PWM = PWM_MAX
	THROTTLE_STOPPED_PWM = PWM_CENTER
	THROTTLE_REVERSE_PWM = PWM_MIN

AUTO_RECORD_ON_THROTTLE = False

CONTROLLER_TYPE = 'HID16CH'

if CONTROLLER_TYPE == 'HID16CH':
	SBUS_DEVICE = '/dev/hidPsoc'
	SBUS_CH1_CENTER = 1027
	SBUS_CH1_MIN = 304
	SBUS_CH1_MAX = 1744
	SBUS_CH2_CENTER = 1024
	SBUS_CH2_MIN = 1744
	SBUS_CH2_MAX = 304
	SBUS_CHX_CENTER = 0x400
	SBUS_CHX_MIN = 304
	SBUS_CHX_MAX = 1744
	SBUS_CH6_CENTER = 0x80
	SBUS_CH7_CENTER = 0x80

	HAVE_LIDAR = True
	if HAVE_LIDAR:
		LIDAR_PWM_PIN = 19
		LIDAR_PWM_FREQ = 100
		LIDAR_LEFT_PWM = 1000
		LIDAR_RIGHT_PWM = 2000

RECORD_DURING_AI = True
